timeout: 3600s
substitutions:
  _REPO: "asm-demo"
  _BUILD_TRIGGER: "push-to-main"
tags:
  - main
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-docker.pkg.dev/${PROJECT_ID}/${_REPO}/frontend','-f', './frontend/Dockerfile' , '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-docker.pkg.dev/${PROJECT_ID}/${_REPO}/frontend']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-docker.pkg.dev/${PROJECT_ID}/${_REPO}/backend','-f', './backend/Dockerfile' , '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-docker.pkg.dev/${PROJECT_ID}/${_REPO}/backend']
images: ['us-docker.pkg.dev/${PROJECT_ID}/${_REPO}/frontend', 'us-docker.pkg.dev/${PROJECT_ID}/${_REPO}/backend']