timeout: 3600s
substitutions:
  _REPO: "asm-demo"
  _BUILD_TRIGGER: "push-to-main"
  _REGION: "us-central1"
tags:
  - main
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/frontend','-f', './frontend/Dockerfile' , './frontend']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/frontend']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/backend','-f', './backend/Dockerfile' , './backend']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/backend']
images: ['${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/frontend', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/backend']