---
services:
  backend:
    build: ./backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5000/ping"]
      interval: 5s
      timeout: 5s
      retries: 12
    restart: always
    expose:
      - "5000"
    ports:
      - 5001:5000
  frontend:
    build: ./frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5000/ping"]
      interval: 5s
      timeout: 5s
      retries: 12
    restart: always
    expose:
      - "5000"
    ports:
      - 5000:5000
