apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    networking.knative.dev/visibility: cluster-local
  name: MODULENAME
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        run.googleapis.com/client-name: cloud-console
      creationTimestamp: null
      name: MODULENAME-VERSION
    spec:
      containerConcurrency: 10
      containers:
      - env:
        - name: MODULE
          value: MODULENAME
        image: us-central1-docker.pkg.dev/potato-05a0/asm-demo/backend:latest
        name: user-container
        ports:
          - containerPort: 5000
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /ping
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /ping
          successThreshold: 1
        resources:
          limits:
            memory: 2Gi
            cpu: 2
          request:
            cpu: 2
            memory: 2Gi
      enableServiceLinks: false
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
---
